export default {
    ru: [
        "Убуд",
        "Чангу",
        "Кута",
        "Семиньяк",
        "Джимбаран",
        "Танджунг Беноа",
        "Нуса Дуа",
        "Амед",
        "Чандидаса и Ловина",
        "Улувату",
        "Кедунгу",
        "Табанан",
        "Унгасан",
        "Легиан",
        "Санур",
        "Умалас",
        "Денпасар",
        "Падонан",
        "Керобокан",
        "Тегаллаланг",
        "Букит",
        "Бадунг",
        "Сингараджа",
        "Керамас",
        "Гианьяр",
        "Сингападу",
        "Сингакерта",
        "Карангсари",
        "Будук",
        "Сукавати",
        "Карангасем",
        "Мунггу",
        "Танах Лот",
    ],
    en: [
        "Ubud",
        "Changu",
        "Kuta",
        "Seminyak",
        "Jimbaran",
        "Tanjung Benoa",
        "Nusa Dua",
        "Amed",
        "Chandidas and Lovina",
        "Uluwatu",
        "Kedungu",
        "Tabanan",
        "Ungasan",
        "Legian",
        "Sanur",
        "Umalas",
        "Denpasar",
        "Padonan",
        "Kerobokan",
        "Tegallalang",
        "Bukit",
        "Badung",
        "Singaraja",
        "Keramas",
        "Gianyar",
        "Singapadu",
        "Singakerta",
        "Karangsari",
        "Buduk",
        "Sukawati",
        "Karangasem",
        "Munggu",
        "Tanakh Lot",
    ]
}